{ mkTarget, lib, ... }:
mkTarget {
  name = "quickshell";
  humanName = "Quickshell";

  configElements =
    {
      colors,
    }:
    let
      theme = ''
        // File generated by Stylix Quickshell target
        pragma Singleton
        import QtQuick

        QtObject {
          // Base16
          property color base00: "#${colors.base00}"
          property color base01: "#${colors.base01}"
          property color base02: "#${colors.base02}"
          property color base03: "#${colors.base03}"
          property color base04: "#${colors.base04}"
          property color base05: "#${colors.base05}"
          property color base06: "#${colors.base06}"
          property color base07: "#${colors.base07}"
          property color base08: "#${colors.base08}"
          property color base09: "#${colors.base09}"
          property color base0A: "#${colors.base0A}"
          property color base0B: "#${colors.base0B}"
          property color base0C: "#${colors.base0C}"
          property color base0D: "#${colors.base0D}"
          property color base0E: "#${colors.base0E}"
          property color base0F: "#${colors.base0F}"

          // Aliases
          property color base: base00
          property color mantle: base01
          property color surface0: base02
          property color surface1: base03
          property color surface2: base04
          property color text: base05
          property color rosewater: base06
          property color lavender: base07
          property color red: base08
          property color peach: base09
          property color yellow: base0A
          property color green: base0B
          property color teal: base0C
          property color blue: base0D
          property color mauve: base0E
          property color flamingo: base0F


          property color background: base00
          property color backgroundAlt: base01
          property color selection: base02
          property color textAlt: base04
          property color warning: base0A
          property color urgent: base09
          property color error: base08
        }
      '';
    in
    {
      xdg.configFile."quickshell/Theme.qml".text = theme;
    };
}
